export default function TermsPage() {
    return (
        <div className="container mx-auto p-4 bg-white text-gray-800 leading-relaxed">
            <h1
                className="text-center text-2xl font-bold text-gray-800"
            >Conditions Générales d’Utilisation </h1>

            <h1 className="text-2xl my-4 font-bold text-gray-800" >I Objet </h1>
            (i) Les présentes Conditions Générales d’Utilisation (ci-après « CGU ») ont pour but de définir les règles d’utilisation de l’application Bus Bi et des services qu’elle propose. Elles établissent les droits et obligations de Bus Bi (ci-après « l’Éditeur ») ainsi que ceux des utilisateurs (ci-après « les Utilisateurs »), qu’ils soient conducteurs ou passagers. Ces conditions encadrent l’accès aux services, leur utilisation et précisent les responsabilités de chaque partie afin d’assurer un usage optimal et sécurisé de la plateforme.
            (ii) L’accès et l’utilisation de l’application Bus Bi implique l’acceptation sans réserve des présentes CGU. En créant un compte, en naviguant sur l’application ou en utilisant ses services, l’Utilisateur reconnaît avoir pris connaissance des CGU, les avoir comprises et acceptées. Cette acceptation constitue un accord juridiquement contraignant entre l’Utilisateur et l’Éditeur. Si l’Utilisateur n’adhère pas à l’une des clauses des CGU, il est prié de ne pas utiliser l’application et de procéder à la suppression de son compte si nécessaire.
            (iii) Les présentes CGU entrent en vigueur dès leur publication sur l’application Bus Bi. La version applicable aux Utilisateurs est celle en vigueur au moment de l’utilisation de l’application. L’Éditeur se réserve le droit de modifier les CGU à tout moment, et ces modifications prennent effet dès leur mise en ligne. Il est recommandé aux Utilisateurs de consulter régulièrement les CGU afin de rester informés des éventuelles mises à jour.
            (iv) Les présentes CGU deviennent opposables aux Utilisateurs dès leur acceptation lors de l’inscription sur l’application Bus Bi. L’Éditeur se réserve le droit de suspendre ou de supprimer tout compte utilisateur en cas de non-respect des CGU. En cas de modification des CGU, l’utilisation continue des services de Bus Bi par l’Utilisateur constitue une acceptation des CGU modifiées. Si l’Utilisateur n’accepte pas les CGU révisées, il doit immédiatement cesser d’utiliser l’application et demander la suppression de son compte.

            <h1 className="text-2xl my-4 font-bold text-gray-800">II Inscription & Services </h1>
            (i) Pour pouvoir accéder et utiliser les services offerts par l’application Bus Bi, les Utilisateurs doivent remplir les critères suivants : avoir au moins 15 ans ; être capable légalement de conclure un contrat ou, si l’Utilisateur est mineur, obtenir l’autorisation de son parent ou tuteur légal ; pour les conducteurs, posséder un permis de conduire valide et en cours de validité, ainsi qu’une assurance automobile couvrant le covoiturage ; ne pas avoir fait l’objet d’une interdiction d’accès à l’application Bus Bi suite à une violation des présentes CGU. L’Éditeur se réserve le droit de vérifier l’éligibilité des Utilisateurs à tout moment et de restreindre l’accès aux services en cas de non-respect des critères mentionnés ci-dessus.
            (ii) L'inscription sur l'application Bus Bi est requise pour accéder aux services de recherche d'itinéraire, de covoiturage, et à tous les autres services offerts par l'application. Pour procéder à l'inscription, l'Utilisateur doit fournir des informations personnelles exactes et complètes, telles que son nom complet, une adresse e-mail valide, un numéro de téléphone, ainsi que, pour les conducteurs, des détails concernant leur véhicule et leur permis de conduire. Après soumission des informations, l’Éditeur enverra un e-mail de validation afin de confirmer la véracité des données fournies. Le compte de l'Utilisateur sera activé uniquement après que celui-ci ait validé les informations. L’Utilisateur assume l'entière responsabilité de la sécurité et de la confidentialité de ses identifiants de connexion.
            (iii) Afin de garantir la sécurité et la conformité des services, Bus Bi exige des conducteurs qu’ils soumettent et fassent vérifier certains documents officiels, tels que le permis de conduire, l’assurance automobile et la carte grise du véhicule. Ces documents doivent être fournis via l'application après l'inscription. Bus Bi utilise des outils de vérification automatisés et manuels pour vérifier l'authenticité de ces documents. Si des documents sont manquants, expirés ou non conformes, l'accès aux services pourra être suspendu ou refusé jusqu'à ce que la situation soit régularisée.
            (iv) Bus Bi se réserve le droit de suspendre temporairement ou de supprimer définitivement le compte d’un Utilisateur dans les situations suivantes : non-respect des présentes CGU ; fourniture d’informations erronées, inexactes ou incomplètes lors de l’inscription ; utilisation frauduleuse de l’application ou des services ; non-conformité aux exigences de vérification des documents. En cas de suspension, l’Utilisateur recevra une notification expliquant les raisons de cette action. L’accès aux services pourra être rétabli une fois les problèmes résolus. En cas de suppression du compte, toutes les informations de l’Utilisateur seront effacées conformément à la Politique de Confidentialité, sauf celles qui doivent être conservées selon la loi.
            (v) Lors de son inscription, l’Utilisateur s’engage à fournir des informations exactes, complètes et à jour ; mettre à jour ses informations personnelles en cas de changement ; ne pas se faire passer pour une autre personne ou utiliser des informations ou documents appartenant à un tiers sans son consentement préalable ; assurer la confidentialité de ses identifiants de connexion et ne pas les partager avec d'autres personnes ; alerter immédiatement Bus Bi en cas d’utilisation non autorisée de son compte ou de toute autre situation compromettant la sécurité. En cas de non-respect de ces engagements, l’Utilisateur pourrait être tenu responsable des conséquences, directes ou indirectes, résultant de ces manquements, y compris des dommages causés à Bus Bi ou à d’autres utilisateurs.

            <h1 className="text-2xl my-4 font-bold text-gray-800">III Description des Services </h1>
            (i) Services de Covoiturage
            Le service de covoiturage de Bus Bi permet aux utilisateurs, qu'ils soient conducteurs ou passagers, de partager des trajets de manière simple, rentable et sécurisée. Les conducteurs peuvent publier des trajets, indiquer le nombre de places disponibles et déterminer un tarif en fonction du trajet. Les passagers peuvent, quant à eux, rechercher des trajets correspondant à leur itinéraire et réserver une ou plusieurs places. Le service de covoiturage inclut la possibilité pour les conducteurs de créer des annonces de trajet en précisant l'itinéraire, les horaires, ainsi que les points de départ et d’arrivée ; un système de recherche qui permet aux passagers de trouver des trajets correspondant à leurs besoins spécifiques ; un processus de réservation en ligne avec paiement intégré, pour une gestion fluide et sécurisée ; un système de notation pour assurer la qualité et la fiabilité du service fourni.
            (ii) Recherche d'Itinéraires de Bus
            Le service de recherche d'itinéraires de bus proposé par Bus Bi permet aux utilisateurs de trouver rapidement les meilleurs trajets en bus en fonction de leurs besoins. Les passagers peuvent saisir leur point de départ et leur destination pour obtenir les options d’itinéraires disponibles, avec des informations détaillées sur les horaires, les arrêts, ainsi que la durée estimée du trajet. Ce service inclut la possibilité de rechercher des itinéraires de bus en fonction de la localisation de départ et de destination ; la fourniture des horaires de passage en temps réel pour chaque ligne de bus ; l'affichage des arrêts intermédiaires et des correspondances disponibles ; des informations détaillées sur la durée du trajet et les options les plus rapides ; un système de notifications en temps réel pour informer les utilisateurs de tout changement ou retard.

            <h1 className="text-2xl my-4 font-bold text-gray-800">IV Utilisation des Services</h1>
            (i) Les conducteurs utilisant les services de Bus Bi s'engagent à fournir un véhicule en excellent état de fonctionnement, conforme aux normes de sécurité applicables, et équipé pour garantir le confort et la sécurité des passagers ; détenir un permis de conduire valide, une assurance automobile couvrant les activités de covoiturage, ainsi que tous les autres documents légaux requis, et veiller à leur mise à jour ; respecter toutes les lois et réglementations en vigueur, y compris celles concernant la vitesse, la circulation et la sécurité routière ; fournir des informations précises et transparentes concernant les trajets proposés, incluant les points de départ et d'arrivée, les horaires ainsi que le nombre de places disponibles ; être ponctuel et respecter les horaires fixés avec les passagers ; adopter un comportement professionnel et courtois, garantissant la sécurité, le confort et une expérience agréable pour les passagers tout au long du trajet.
            (ii) Les passagers utilisant les services de Bus Bi s'engagent à fournir des informations précises et complètes lors de la réservation des trajets, y compris leurs coordonnées de contact ; respecter les horaires de départ fixés avec le conducteur et avertir immédiatement en cas de retard ou d'annulation ; ne pas endommager le véhicule du conducteur ni le salir de manière excessive ; adopter un comportement respectueux et courtois envers le conducteur et les autres passagers.
            (iii) La sécurité est une priorité pour Bus Bi et ses utilisateurs. Les conducteurs et passagers doivent respecter les engagements suivants : l'utilisation des ceintures de sécurité est obligatoire pour tous les passagers du véhicule ; les limites de vitesse et les règles de circulation doivent être strictement respectées ; la consommation d'alcool ou de substances illicites est interdite avant et pendant le trajet ; tout comportement dangereux ou inapproprié doit être signalé immédiatement au service client de Bus Bi ; les mesures sanitaires en vigueur, y compris l'hygiène personnelle et la propreté du véhicule, doivent être respectées.
            (iv) En cas de non-respect des présentes CGU, Bus Bi se réserve le droit de prendre les mesures suivantes : envoi d’un avertissement formel à l'utilisateur concerné ; suspension temporaire ou permanente du compte utilisateur ; suppression définitive du compte utilisateur, avec interdiction de créer un nouveau compte ; signalement aux autorités compétentes en cas de violation de la législation en vigueur. Ces sanctions seront appliquées par Bus Bi en fonction de la gravité des infractions et des éventuelles récidives. L'utilisateur sera informé de la sanction par e-mail ou via l'application.
            <h1 className="text-2xl my-4 font-bold text-gray-800">V Tarifs et Paiements</h1>
            (i) Pour les passagers, Bus Bi applique des frais de dépôt ou de paiement lors de la réservation d’un trajet. Ces frais sont clairement indiqués avant la confirmation de la réservation. En ce qui concerne les conducteurs, Bus Bi prélève une commission sur chaque trajet effectué, dont le pourcentage est spécifié au moment de la création de l’offre de covoiturage. Bus Bi ne prélève aucun frais pour les retraits effectués par les conducteurs.
            (ii) Bus Bi accepte les paiements via les services de mobile money Orange et Wave. Ces modes de paiement permettent aux utilisateurs de régler leurs réservations et frais en toute sécurité et simplicité.
            (iii) Les remboursements sur Bus Bi sont effectués conformément à la politique de remboursement de la plateforme. Les cas dans lesquels un remboursement peut être accordé incluent, mais ne se limitent pas à : annulation d'une réservation par le conducteur après confirmation ; non-respect des conditions du trajet par le conducteur ; problèmes techniques empêchant la réalisation du trajet. Les remboursements sont effectués via le mode de paiement utilisé lors de la réservation.
            (iv) En cas de litige financier, Bus Bi invite les utilisateurs à contacter le service client via l’application ou par e-mail. Les réclamations doivent être soumises dans un délai raisonnable après la transaction concernée. Bus Bi s’engage à traiter chaque réclamation rapidement et à rechercher une solution amiable en collaboration avec les parties concernées. Si aucune solution amiable ne peut être trouvée, le litige pourra être soumis à une médiation.

            <h1 className="text-2xl my-4 font-bold text-gray-800">VI Annulation et Politique de Remboursement</h1>
            (i) Le conducteur a la possibilité d’annuler un trajet après avoir accepté une réservation, mais il doit le faire dans les plus brefs délais afin de minimiser l’impact sur le passager. En cas d'annulation tardive (moins de 6 heures avant l'heure de départ prévue), des pénalités peuvent être appliquées, telles que la suspension temporaire du compte du conducteur ou une diminution de son évaluation par les utilisateurs. Les annulations fréquentes et non justifiées peuvent entraîner la suspension définitive du compte du conducteur.
            (ii) Le passager peut annuler sa réservation à tout moment avant le départ du trajet. Cependant, en cas d’annulation tardive (moins de 6 heures avant l'heure prévue de départ), des frais d’annulation a auteur de 50% seront appliqués. Le montant de ces frais sera indiqué lors du processus d’annulation. Aucun remboursement ne sera effectué si l’annulation intervient après le début du trajet.
            (iii) Les annulations abusives, qu'elles concernent le conducteur ou le passager, sont strictement interdites. Une annulation sera considérée comme abusive si elle est répétée, injustifiée, ou réalisée dans le but de nuire à l'autre partie. À partir de trois annulations consécutives, l'annulation sera systématiquement considérée comme abusive. Bus Bi se réserve le droit d'appliquer des sanctions en cas d'annulation abusive, telles que : la suspension temporaire ou permanente du compte utilisateur ; l'application de frais supplémentaires ; la diminution de l'évaluation ou du score de fiabilité de l'utilisateur. De plus, Bus Bi peut refuser d'effectuer des remboursements dans les cas d'annulation abusive, conformément aux présentes CGU.

            <h1 className="text-2xl my-4 font-bold text-gray-800">VII Contrôle des Documents Essentiels</h1>
            (i) Afin d'assurer la sécurité et la conformité des services proposés par Bus Bi, tous les conducteurs doivent soumettre et maintenir à jour les documents suivants : un permis de conduire valide et en cours de validité, adapté au type de véhicule utilisé ; une assurance automobile en cours de validité, couvrant le covoiturage, incluant une couverture de responsabilité civile ; le document officiel attestant de l'enregistrement légal du véhicule utilisé pour les trajets ; un certificat valide attestant que le véhicule a passé avec succès un contrôle technique et est en bon état de fonctionnement ; une pièce d'identité officielle (passeport, carte d’identité nationale) pour vérifier l'identité du conducteur.
            (ii) Afin de garantir la conformité continue des conducteurs, Bus Bi a mis en place des mécanismes d’alerte pour informer les conducteurs de l’expiration imminente de leurs documents obligatoires. Ces alertes comprennent : l'envoi d’une notification par l’application et par e-mail 30 jours avant la date d’expiration d’un document ; l'envoi de notifications répétées 10 jours et 5 jours avant l’expiration, si le conducteur n’a pas encore mis à jour son document ; et si un document expire sans avoir été mis à jour, le compte du conducteur sera temporairement suspendu jusqu’à ce que le document soit renouvelé et validé.



            <h1 className="text-2xl my-4 font-bold text-gray-800">VIII Notifications et Communication</h1>
            (i) Bus Bi utilise différents types de notifications pour tenir les utilisateurs informés des événements importants liés à l’utilisation de l’application. Ces notifications comprennent, mais ne sont pas limitées à : la confirmation, l'annulation ou la modification d’une réservation de trajet ; des rappels concernant la sécurité pendant les trajets, ainsi que des mises à jour sur les conditions météorologiques ou de circulation ; la confirmation des paiements effectués, des alertes de facturation et des rappels pour les abonnements ; des notifications concernant l’expiration prochaine des documents requis pour les conducteurs ; des informations sur les promotions, réductions et offres spéciales disponibles pour les utilisateurs ; ainsi que des mises à jour importantes de l’application, des modifications des CGU et d'autres communications administratives.
            (ii) Bus Bi s’efforce de garantir l’envoi en temps utile de toutes les notifications et alertes. Cependant, Bus Bi décline toute responsabilité en cas de non-réception de notifications dues à des facteurs échappant à son contrôle, tels que des pannes de réseau, des problèmes de connexion Internet ou de réseau mobile de l’utilisateur, des notifications bloquées ou désactivées sur le dispositif de l’utilisateur, ou une configuration incorrecte des paramètres de notification, ainsi que des e-mails envoyés dans les dossiers de spam ou de courriers indésirables par le fournisseur de messagerie de l’utilisateur.
            (iii) Bus Bi permet aux utilisateurs de communiquer directement entre eux via les coordonnées des utilisateurs intégrées à l’application, principalement pour organiser les détails du trajet ou discuter des conditions de transport. Ces communications doivent être utilisées de manière responsable et respecter les règles suivantes : le respect et la courtoisie, où les messages doivent être respectueux, exempts de propos injurieux, discriminatoires ou offensants ; l'usage approprié, où les communications doivent se limiter aux questions liées au trajet ou au transport, toute utilisation abusive, telle que le spam ou le harcèlement, étant strictement interdite ; et la confidentialité, où les utilisateurs ne doivent pas partager d’informations personnelles sensibles via les messages internes de l’application. Bus Bi ne peut être tenu responsable des informations échangées directement entre les utilisateurs.

            <h1 className="text-2xl my-4 font-bold text-gray-800">IX Propriété Intellectuelle</h1>
            (i) L’ensemble des éléments constituant l’application Bus Bi, incluant, mais sans s’y limiter, les textes, graphiques, logos, icônes, images, clips audio, logiciels, bases de données, et codes, sont la propriété exclusive de Bus Bi ou sont utilisés sous licence. Ces éléments sont protégés par les lois en vigueur sur la propriété intellectuelle, incluant les droits d’auteur, les marques de commerce, les brevets, et les secrets commerciaux.
            (ii) Bus Bi accorde aux utilisateurs une licence limitée, non exclusive, non transférable et révocable d’accès et d’utilisation de l’application Bus Bi à des fins strictement personnelles et non commerciales, conformément aux présentes CGU. Cette licence n’accorde aucun droit de propriété aux utilisateurs sur l’application ou sur ses éléments constitutifs.
            (iii) Les utilisateurs conservent la propriété des contenus qu’ils soumettent via l’application Bus Bi, tels que les évaluations, commentaires, photos de profil, ou autres informations. En soumettant ces contenus, les utilisateurs accordent à Bus Bi une licence mondiale, non exclusive, gratuite et transférable d’utiliser, reproduire, distribuer, afficher et modifier ces contenus dans le cadre de l’exploitation de l’application.
            (iv) En cas de violation des droits de propriété intellectuelle de Bus Bi ou de tout tiers, l’utilisateur concerné s’expose à des sanctions, incluant, mais sans s’y limiter : la suspension ou la suppression définitive de son compte ; des poursuites judiciaires pour violation des droits de propriété intellectuelle ; et le paiement de dommages-intérêts pour compenser les préjudices subis par Bus Bi ou les titulaires des droits.

            <h1 className="text-2xl my-4 font-bold text-gray-800">X Responsabilités</h1>

            (i) Bus Bi s’engage à faire tout son possible pour assurer le bon fonctionnement de l’application et la sécurité des services fournis. Cependant, la responsabilité de Bus Bi ne saurait être engagée en cas de dysfonctionnements techniques affectant l’accès ou l’utilisation de l’application, quels qu’en soient la cause ou la durée ; de dommages directs ou indirects résultant de l’utilisation ou de l’incapacité à utiliser l’application, y compris la perte de données, les interruptions de service, ou les erreurs ; et de dommages causés par une utilisation non conforme de l’application par les utilisateurs ou par des tiers non autorisés.

            (ii) L’application Bus Bi peut contenir des liens vers des services ou des contenus fournis par des tiers (ex. : passerelles de paiement, services de géolocalisation). Bus Bi n’exerce aucun contrôle sur ces services tiers et ne peut être tenue responsable de leur contenu, fonctionnement, ou conformité aux lois en vigueur. Les utilisateurs accèdent à ces services tiers sous leur propre responsabilité et sont invités à consulter les conditions d’utilisation de ces services avant de les utiliser.

            <h1 className="text-2xl my-4 font-bold text-gray-800">XI Résiliation de Compte et Exclusion</h1>

            (i) L’utilisateur peut résilier son compte Bus Bi à tout moment et sans motif particulier. Pour ce faire, il doit accéder aux paramètres de son compte dans l’application et suivre la procédure de résiliation. La résiliation prend effet immédiatement après la confirmation de la demande par l’utilisateur. Toutefois, Bus Bi se réserve le droit de conserver certaines informations de l’utilisateur pour la durée nécessaire au respect des obligations légales ou pour la résolution de litiges en cours.

            (ii) Bus Bi se réserve le droit de suspendre ou de résilier le compte d’un utilisateur en cas de non-respect des présentes CGU ou de comportement jugé inapproprié, nuisible ou illégal. Les motifs de résiliation peuvent inclure, mais ne sont pas limités à la violation répétée des règles de conduite définies dans les CGU, la soumission de documents frauduleux ou non conformes, l’utilisation abusive ou frauduleuse des services de Bus Bi, et toute activité illégale ou non autorisée via l’application. Avant toute résiliation, Bus Bi informera l’utilisateur des motifs de cette décision et lui donnera la possibilité de fournir des explications. En cas de résiliation, l’utilisateur recevra une notification par e-mail ou via l’application.

            (iii) En cas de résiliation du compte, que celle-ci soit à l’initiative de l’utilisateur ou de Bus Bi, les conséquences suivantes s’appliquent : l’utilisateur perd l’accès à son compte ainsi qu’à toutes les données associées (réservations, historiques de trajets, évaluations, etc.) ; Les services de Bus Bi ne seront plus accessibles à l’utilisateur résilié ; Les crédits, abonnements, ou autres avantages non utilisés à la date de résiliation ne seront pas remboursés, sauf disposition contraire des présentes CGU ; Bus Bi se réserve le droit de conserver certaines informations de l’utilisateur, conformément à sa Politique de Confidentialité, pour le respect des obligations légales et réglementaires.

            (iv) Si un utilisateur estime que la résiliation de son compte est injustifiée, il peut soumettre une réclamation en contactant le service client de Bus Bi dans un délai de 15 jours suivant la notification de résiliation. Bus Bi s’engage à examiner la réclamation et à fournir une réponse motivée dans un délai raisonnable. Si, après examen, Bus Bi reconnaît que la résiliation était infondée, le compte de l’utilisateur sera réactivé et, le cas échéant, les services non utilisés seront restitués ou compensés.

            <h1 className="text-2xl my-4 font-bold text-gray-800">XII Données Personnelles et Confidentialité</h1>
            (i) Bus Bi, éditée par Bus Bi SAS, collecte certaines données personnelles des utilisateurs afin de fournir et d'améliorer les services proposés. Ces données incluent, mais ne sont pas limitées à : Informations d’identification : nom, prénom, adresse e-mail, numéro de téléphone, photo de profil ; Informations de paiement : détails des cartes de crédit ou des comptes de paiement électronique ; Données de localisation : position géographique en temps réel, itinéraires, points de départ et d’arrivée ; Données relatives au véhicule (pour les conducteurs) : marque, modèle, immatriculation, état du véhicule ; Historique d’utilisation : historique des trajets, réservations effectuées, évaluations et commentaires laissés.
            (ii) Les données personnelles collectées par Bus Bi sont traitées conformément aux lois en vigueur et sont utilisées à des fins spécifiques, telles que : Fourniture des services : gestion des réservations, paiements, communications entre utilisateurs ; Amélioration de l’expérience utilisateur : personnalisation des services, recommandations basées sur les préférences ; Sécurité et conformité : vérification des documents, prévention des fraudes, respect des obligations légales ; Marketing et promotion : envoi de promotions, notifications sur les offres spéciales (avec le consentement de l’utilisateur) ; Analyse statistique : évaluation de l’utilisation des services, études de marché. Les données ne sont partagées avec des tiers que dans la mesure nécessaire à la fourniture des services (ex. : partenaires de paiement) ou si la loi l’exige.
            (iii) Bus Bi met en œuvre des mesures techniques et organisationnelles appropriées pour protéger les données personnelles des utilisateurs contre tout accès non autorisé, divulgation, modification ou destruction. Ces mesures incluent : Cryptage des données : les informations sensibles, telles que les données de paiement, sont cryptées pendant leur transmission et leur stockage ; Contrôles d’accès : l’accès aux données personnelles est limité aux employés autorisés et aux prestataires de services, sur une base strictement nécessaire ; Sauvegardes régulières : les données sont sauvegardées régulièrement pour prévenir la perte ou l’altération accidentelle. Les utilisateurs sont également responsables de la confidentialité de leurs identifiants de connexion et doivent veiller à ne pas les divulguer à des tiers.

            <h1 className="text-2xl my-4 font-bold text-gray-800">XII Autres</h1>

            (i) Les présentes Conditions Générales d'Utilisation (CGU), ainsi que tout autre document ou politique expressément mentionné(e) dans celles-ci, constituent l'intégralité de l'accord entre les utilisateurs et Bus Bi concernant l'utilisation de l'application. Elles remplacent et annulent tous accords, promesses ou discussions antérieurs, qu'ils soient oraux ou écrits, relatifs à l'objet des présentes CGU.

            (ii) Les présentes CGU entrent en vigueur à compter de leur acceptation par l’utilisateur lors de son inscription à l’application Bus Bi. Bus Bi se réserve le droit de modifier, compléter ou mettre à jour les présentes CGU à tout moment, à sa seule discrétion. En cas de modification substantielle, les utilisateurs seront informés via l’application ou par e-mail. Les utilisateurs seront tenus d’accepter les modifications des CGU pour continuer à utiliser les services de Bus Bi. En cas de désaccord avec les nouvelles CGU, l’utilisateur devra cesser d’utiliser l’application et pourra résilier son compte conformément à l’article 11 des présentes CGU.

        </div>
    );
}